### ISSUE TITLE
Adapt better to narrow screens

### ISSUE THREAD

**Issue by gwicke** [vector-im/vector-web#1633]
Narrow screens are common on mobile, and when using vector in a narrow sidebar-style window on a desktop. Here are some styling ideas that could help to maximize the content visible on small screens:

- Completely hide the user list by default.
- Hide user icons in chat messages, and reduce margins around messages to a bare minimum. Possibly, set off user names / message boundaries slightly by making them left-bound, and indenting messages a couple of pixels.

**Comment by gwicke** [comment]
Rough sample styles:
```css
/* Disable link previews */
.mx_LinkPreviewWidget {
    display: none
}
@media screen and (max-width: 800px) {
    .mx_EventTile_avatar {
        /* TODO: There might be a better way to minimize it while it's collapsed */
        display: none
    }

    /* Reduce spacing in content area */
    .mx_EventTile {
        margin-left: 0;
        margin-top: 5px;
    }
    .mx_EventTile_line {
        margin-left: 10px;
        margin-right: 5px;
    }
    .mx_MatrixChat_middlePanel {
        padding-right: 0px !important;
        padding-left: 5px !important;
    }
    .mx_RoomView_statusAreaBox {
        min-height: 0;
    }
    .mx_RoomStatusBar {
        margin-top: 0;
        min-height: 0;
    }
}
```
