### ISSUE TITLE
Hoverover doesn't work for showing room membership timestamps

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#59]

**Comment by Kegsay** [comment]
Also doesn't work for call events, etc. It looks like the offending code (CSS) is:
```css
.mx_MessageTile:hover .mx_MessageTimestamp {
    display: block;
}
```

And I'm *guessing* that these events don't have `mx_MessageTile` as their class?
