### ISSUE TITLE
On linux chrome, github highlighted codeblock horizontal scrollbar can overlap with the next msg and get lost

### ISSUE THREAD

**Issue by matrixbot** [vector-im/vector-web#754]
Created by @ matthew:matrix.org.

**Comment by ara4n** [comment]
See https://matrix.org/_matrix/media/v1/download/jki.re/niqajBJeKEKZKMJwcRGpoWbh

**Comment by erikjohnston** [comment]
Removing the following removes the bug (but changes layout):

```css
.mx_EventTile_continuation {
    margin-top: 8px!important;
}
```
